openapi: 3.0.0
info:
  title: Backend Communication Patterns API
  description: API documentation for different communication patterns in backend systems.
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  